# Generated by Django 5.0.1 on 2024-01-23 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking', models.CharField(max_length=100, unique=True)),
                ('direccion_destinatario', models.CharField(max_length=200)),
                ('telefono_destinatario', models.CharField(max_length=20)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('estado', models.CharField(choices=[('deposito', 'En deposito'), ('distribucion', 'En distribucion')], max_length=20)),
                ('tipo_paquete', models.CharField(choices=[('P', 'Peso Menor 1000'), ('M', 'Peso Menor 3000'), ('G', 'Todo lo demas')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField()),
                ('motivo_fallo', models.CharField(blank=True, max_length=255, null=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_planilla', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planilla_items', to='logistics.paquete')),
            ],
        ),
    ]
