# Generated by Django 5.0.1 on 2024-01-23 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='item',
        ),
        migrations.AddField(
            model_name='itemplanilla',
            name='planilla',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.planilla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planilla',
            name='items_planilla',
            field=models.ManyToManyField(related_name='planilla_items', to='logistics.itemplanilla'),
        ),
        migrations.AlterField(
            model_name='itemplanilla',
            name='motivo_fallo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemplanilla',
            name='posicion',
            field=models.PositiveIntegerField(),
        ),
    ]
