# Generated by Django 5.0.1 on 2024-01-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_planilla_item_itemplanilla_planilla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemplanilla',
            name='motivo_fallo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
